# arty_synth.xdc - constraints for arty_synth (synth_top board build, issue #76)
#
# Digilent Arty A7 + Pmod I2S2 (on Pmod header JA). The system and audio clocks
# are generated by the on-board MMCM from the 100 MHz oscillator, so only the
# 100 MHz input is a primary clock; sys_clk / mclk are derived automatically.
# The serial bit clock BCLK is divided from mclk in fabric by i2s_clkgen, so it
# is declared as a generated clock and the mesh (sys_clk) / audio (bclk) domains
# are constrained as an asynchronous crossing (matching arty_a7.xdc).

#==============================================================================
# Primary clock: 100 MHz oscillator
#==============================================================================
set_property -dict { PACKAGE_PIN E3 IOSTANDARD LVCMOS33 } [get_ports clk100]
create_clock -name clk100 -period 10.000 [get_ports clk100]

#==============================================================================
# Buttons / switches (reset + preset controls)
#==============================================================================
## btn0 reset, btn1 preset recall, btn2 preset save
set_property -dict { PACKAGE_PIN D9  IOSTANDARD LVCMOS33 } [get_ports {btn[0]}]
set_property -dict { PACKAGE_PIN C9  IOSTANDARD LVCMOS33 } [get_ports {btn[1]}]
set_property -dict { PACKAGE_PIN B9  IOSTANDARD LVCMOS33 } [get_ports {btn[2]}]
set_property -dict { PACKAGE_PIN B8  IOSTANDARD LVCMOS33 } [get_ports {btn[3]}]
## slide switches -> preset index
set_property -dict { PACKAGE_PIN A8  IOSTANDARD LVCMOS33 } [get_ports {sw[0]}]
set_property -dict { PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports {sw[1]}]
set_property -dict { PACKAGE_PIN C10 IOSTANDARD LVCMOS33 } [get_ports {sw[2]}]
set_property -dict { PACKAGE_PIN A10 IOSTANDARD LVCMOS33 } [get_ports {sw[3]}]
## active-voice LEDs
set_property -dict { PACKAGE_PIN H5  IOSTANDARD LVCMOS33 } [get_ports {led[0]}]
set_property -dict { PACKAGE_PIN J5  IOSTANDARD LVCMOS33 } [get_ports {led[1]}]
set_property -dict { PACKAGE_PIN T9  IOSTANDARD LVCMOS33 } [get_ports {led[2]}]
set_property -dict { PACKAGE_PIN T10 IOSTANDARD LVCMOS33 } [get_ports {led[3]}]

#==============================================================================
# Pmod I2S2 codec (Pmod header JA) + MIDI in
#==============================================================================
## JA1 MCLK, JA2 LRCLK, JA3 BCLK, JA4 SDIN (to DAC)
set_property -dict { PACKAGE_PIN G13 IOSTANDARD LVCMOS33 } [get_ports codec_mclk]
set_property -dict { PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports codec_lrclk]
set_property -dict { PACKAGE_PIN A11 IOSTANDARD LVCMOS33 } [get_ports codec_bclk]
set_property -dict { PACKAGE_PIN D12 IOSTANDARD LVCMOS33 } [get_ports codec_sdin]
## serial MIDI in (opto-isolated 31250 baud) on JA7
set_property -dict { PACKAGE_PIN D13 IOSTANDARD LVCMOS33 } [get_ports midi_rx]

#==============================================================================
# Clock-domain crossing (mesh sys_clk  <->  audio bclk)
#==============================================================================
# BCLK is mclk/4, produced by i2s_clkgen in fabric; declare it as a generated
# clock so the tools see the audio domain. (Adjust the source pin/net name to
# the elaborated design if the auto-inference does not pick it up.)
create_generated_clock -name bclk -source [get_pins -hier -filter {NAME =~ *i2s_clkgen*bclk_i_reg*/C}] \
  -divide_by 4 [get_pins -hier -filter {NAME =~ *i2s_clkgen*bclk_i_reg*/Q}]

# The mesh (sys_clk) and audio (bclk) domains are independent: cut setup/hold on
# the crossing (the cdc_word MCP handshake relies on this) and bound the
# multi-bit pickup word's skew so it cannot tear.
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks clk100] \
  -group [get_clocks bclk]

set_bus_skew -from [get_cells -hierarchical -filter {NAME =~ *cdc_pick/hold_reg*}] \
             -to   [get_cells -hierarchical -filter {NAME =~ *cdc_pick/dst_data_reg*}] 81.380

# Asynchronous inputs (buttons, MIDI): do not time their capture edge.
set_false_path -from [get_ports {btn[*] sw[*] midi_rx}]
