import { existsSync as nativeBaselineExists } from "node:fs";
if (nativeBaselineExists(new URL("../NATIVE_BASELINE.json", import.meta.url))) throw new Error("Repaired native PCB is authoritative. Use hardware/refresh_outputs.py. Run legacy reconstruction only in a separate experimental copy without NATIVE_BASELINE.json.");
/**
 * Fabrication and toolchain outputs.
 *
 * Everything that is a standard circuit-json conversion is delegated to
 * `tsci export`. The one artifact tscircuit cannot produce is the Vivado pin
 * constraints file: it is the board's half of the contract with the RTL in
 * `src/rtl/synth_top.vhd`, and it is generated here from the same `io` map the
 * schematic uses so the two cannot drift apart.
 */
import { spawnSync } from "node:child_process"
import { mkdirSync, writeFileSync } from "node:fs"
import pins from "../fpga-pins.json"
import { io } from "../design"

const OUT = "dist"
const ENTRY = "courant.circuit.tsx"
mkdirSync(OUT, { recursive: true })

// `kicad_pcb` is the handoff: `scripts/route.py` takes it from here, through
// Freerouting and back, and `scripts/fab.py` plots the Gerbers from the result.
//
// `specctra-dsn` is deliberately NOT in this list, even though tscircuit offers
// it. Its converter places every component `side: "front"` regardless of the
// layer it is on, which silently moves all 38 back-side BGA decoupling
// capacitors to the top of the board, and it throws outright on a pad with a
// null `pcb_component_id` -- which is what this board's three fiducials emit.
// KiCad writes the DSN instead, from the board below; see scripts/route.py.
//
// Gerbers are likewise not exported here. They are plotted from the *routed*
// board by scripts/fab.py, which refuses to run on an unrouted one: Gerbers
// with pads, mask and drills but no copper look exactly like fabrication data
// and are not.
const formats: [string, string][] = [
  ["circuit-json", "courant.circuit.json"],
  ["readable-netlist", "courant.netlist.txt"],
  ["schematic-svg", "courant.schematic.svg"],
  ["pcb-svg", "courant.pcb.svg"],
  ["kicad_pcb", "courant.kicad_pcb"],
]

let failed = 0
for (const [format, file] of formats) {
  const r = spawnSync("tsci", ["export", ENTRY, "-f", format, "-o", `${OUT}/${file}`, "--disable-parts-engine"], {
    stdio: "inherit",
  })
  if (r.status !== 0) { console.error(`  export ${format} failed`); failed++ }
}

// ------------------------------------------------------- Vivado constraints ---
const byBall = Object.fromEntries(pins.map((p) => [p.ball, p]))
// Ports the RTL drives or samples directly, in synth_top.vhd's spelling.
const rename: Record<string, string> = {
  clk100: "clk100", audio_mclk_in: "mclk", midi_rx: "midi_rx", reset_n: "reset_n",
  cv_select: "cv_sel", gate: "gate",
  dac_mclk: "codec_mclk", dac_bclk: "codec_bclk", dac_lrclk: "codec_lrclk",
  dac_data: "sd_tx", dac_unmute: "dac_unmute",
  adc_sclk: "adc_sclk", adc_mosi: "adc_mosi", adc_miso: "adc_miso", adc_cs_n: "adc_cs_n",
  enc_a: "enc_a", enc_b: "enc_b", enc_btn_n: "enc_btn_n",
  led0: "active[0]", led1: "active[1]", led2: "active[2]", led3: "active[3]",
}
const lines = [
  "# courant_rev_a.xdc - pin constraints for the Courant standalone board (Rev A).",
  "#",
  "# GENERATED by hardware/courant/scripts/export.ts from the board's `io` map.",
  "# Do not edit by hand: change design.ts and re-run `npm run export`.",
  "#",
  "# These are the board's pins. They constrain a board-level top wrapper for",
  "# this PCB, analogous to syn/vivado/arty_synth.vhd for the Arty A7 -- that",
  "# wrapper is not written yet, and it additionally needs an SPI master to read",
  "# the MCP3208 into synth_top's pitch_cv / mod_cv / pot_* sample ports.",
  "#",
  "# Every bank in use has its VCCO tied to 3.3 V on the board, so all user I/O",
  "# is LVCMOS33. Board net names are given in the trailing comment.",
  "",
  "#" + "=".repeat(78),
  "# Clocks: separate 100 MHz system and 12.288 MHz audio oscillators, so the",
  "# audio master clock carries no fractional-MMCM error.",
  "#" + "=".repeat(78),
]
const clocks: Record<string, number> = { clk100: 10.0, mclk: 81.38 }
for (const [ball, net] of Object.entries(io)) {
  const port = rename[net]
  if (!port) continue
  if (!(port in clocks)) continue
  lines.push(
    `set_property -dict { PACKAGE_PIN ${ball} IOSTANDARD LVCMOS33 } [get_ports ${port}]`,
    `create_clock -name ${port} -period ${clocks[port].toFixed(3)} [get_ports ${port}]`,
  )
}
const groups: [string, RegExp][] = [
  ["Audio codec (PCM5102A, FPGA is I2S master)", /^(codec_|sd_tx|dac_unmute)/],
  ["Panel ADC (MCP3208 over SPI)", /^adc_/],
  ["Panel controls and CV", /^(enc_|cv_sel|gate|reset_n)/],
  ["MIDI in (opto-isolated, 31250 baud)", /^midi_/],
  ["Voice activity LEDs", /^active/],
]
for (const [title, re] of groups) {
  lines.push("", "#" + "=".repeat(78), `# ${title}`, "#" + "=".repeat(78))
  for (const [ball, net] of Object.entries(io)) {
    const port = rename[net]
    if (!port || port in clocks || !re.test(port)) continue
    const p = byBall[ball]
    lines.push(
      `set_property -dict { PACKAGE_PIN ${ball} IOSTANDARD LVCMOS33 } [get_ports {${port}}]  ;# ${net}, bank ${p.bank}`,
    )
  }
}
lines.push(
  "",
  "#" + "=".repeat(78),
  "# Asynchronous inputs. Each is synchronised in fabric before use; constrain",
  "# them as false paths so they do not gate timing closure.",
  "#" + "=".repeat(78),
  "set_false_path -from [get_ports {enc_a enc_b enc_btn_n gate cv_sel midi_rx reset_n}]",
  "",
  "#" + "=".repeat(78),
  "# Configuration: master SPI from the on-board W25Q64JV, 3.3 V config bank.",
  "#" + "=".repeat(78),
  "set_property CFGBVS VCCO [current_design]",
  "set_property CONFIG_VOLTAGE 3.3 [current_design]",
  "set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 1 [current_design]",
  "set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]",
  "",
)
writeFileSync(`${OUT}/courant_rev_a.xdc`, lines.join("\n"))
console.log(`wrote ${OUT}/courant_rev_a.xdc (${Object.keys(rename).length} ports)`)
process.exit(failed ? 1 : 0)
